POST http://localhost:5000/userTask/createUserTask
Content-Type: application/json

{
    "taskTitle":"aaaaaaa",
    "taskDescription":"bbbbbbbbbbbb"
}

###
POST http://tranquil-escarpment-92025.herokuapp.com/userTask/createUserTask
Content-Type: application/json

{
    "taskTitle":"deploy to heroku",
    "taskDescription":"important to connect client app with server"
}

###

GET http://localhost:5000/userTask/getUserTask

###

GET http://tranquil-escarpment-92025.herokuapp.com/userTask/getUserTask

###
PATCH http://localhost:5000/userTask/updateTask/5fabdfbbbd78883ad48e8a63
Content-Type: application/json

{
    "taskTitle":"updating done!"

}
